[package]
name = "opengl"
version = "0.1.0"
authors = ["Gabriel Borges Gutierrez <gabriel.bgs00@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.29.0"
glutin = "0.26.0"
